name: sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Sync files
        run: |
          composer sync-parser-class
          composer sync-markdown-class

      - name: Set current date as env variable
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Sync $TODAY
          branch: sync
          delete-branch: true
          title: Sync $TODAY
          body: |
            Sync classes from WordPress.org repository.
