name: test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - ".github/workflows/wp.yml"
      - "**.php"
      - "composer.json"
      - "phpcs.xml.dist"
      - "phpstan.neon.dist"
      - "phpunit.xml.dist"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/wp.yml"
      - "**.php"
      - "composer.json"
      - "phpcs.xml.dist"
      - "phpstan.neon.dist"
      - "phpunit.xml.dist"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']

    env:
      WP_DB_TEST_NAME: wp_test
      WP_DB_TEST_PASS: wp_test
      WP_DB_TEST_USER: wp_test
      PHP_EXTENSIONS: mysqli

    services:
      database:
        image: 'mariadb:10.11.5'
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ env.WP_DB_TEST_NAME }}
          MYSQL_USER: ${{ env.WP_DB_TEST_USER }}
          MYSQL_PASSWORD: ${{ env.WP_DB_TEST_PASS }}
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup PHP extensions cache environment
        id: php-ext-cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          key: php-${{ matrix.php }}-ext

      - name: Setup PHP extensions cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.php-ext-cache.outputs.dir }}
          key: ${{ steps.php-ext-cache.outputs.key }}
          restore-keys: ${{ steps.php-ext-cache.outputs.key }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Setup Composer cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          tools: composer:v2

      - name: Install dependencies
        run: |
          composer remove syntatis/coding-standard rector/rector --dev
          composer install --prefer-dist

      - name: Run test
        env:
          WP_DB_TEST_HOST: 127.0.0.1:${{ job.services.database.ports['3306'] }}
          WP_ENVIRONMENT_TYPE: development
        run: |
          vendor/bin/phpunit
